---
abstract: 'Redis-compatible storage using SQLite on the back-end.'
author:
  - 'Steve Kemp <steve@steve.org.uk>'
build_requires:
  Test::More: '0'
  Test::NoTabs: '0'
  Test::Pod: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Redis-SQLite
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  perl: '5.008'
resources:
  GitMirror: http://git.steve.org.uk/cpan/Redis--SQLite
  bugtracker: https://github.com/skx/Redis--SQLite/issues
  homepage: https://github.com/skx/Redis--SQLite/
  license: http://dev.perl.org/licenses/
  repository: https://github.com/skx/Redis--SQLite.git
version: '0.1'
